### ISSUE TITLE
Error loading recipes in lwc component

### ISSUE THREAD

**Issue by EstebanRomero84** [trailheadapps/apex-recipes#19]
![image](https://user-images.githubusercontent.com/30849643/96204427-aecb2200-0f3a-11eb-8bf9-6d8cbe5364a3.png)

Stack:

SYSTEM_METHOD_ENTRY|[1]|Pattern.Pattern()
SYSTEM_METHOD_EXIT|[1]|Pattern
METHOD_ENTRY|[21]||System.Pattern.compile(String)
METHOD_EXIT|[21]||System.Pattern.compile(String)
METHOD_ENTRY|[24]||System.Pattern.matcher(String)
METHOD_EXIT|[24]||System.Pattern.matcher(String)
METHOD_ENTRY|[25]||System.Matcher.find()
METHOD_EXIT|[25]||System.Matcher.find()
METHOD_EXIT|[120]|01pf400000MUm5y|ApexClassUtilities.getGroupFromClassBody(ApexClass)
METHOD_EXIT|[66]|01pf400000MUm6l|RecipeTreeViewController.generateMapOfGroupToListOfNames()
FATAL_ERROR|System.LimitException: Regex too complicated

Class.System.Matcher.find: line 26, column 1
Class.ApexClassUtilities.getGroupFromClassBody: line 25, column 1
Class.RecipeTreeViewController.generateMapOfGroupToListOfNames: line 120, column 1
Class.RecipeTreeViewController.generateTreeData: line 66, column 1
FATAL_ERROR|System.LimitException: Regex too complicated

ApexClass:
Name=fflib_MatcherDefinitionsTest, Body=/**

**Comment by codefriar** [comment]
@EstebanRomero84 - Thanks for the note! 

I suspect you may be installing Apex Recipes in a dev org or sandbox that already has pre-existing code. We try to call out in the readme that you should use a _**new**_ de org, or use a Scratch org, but I want to make that clearer. 

Because of the way the tree view picks up classes and tries to sort them, if the org you installed in already has a bunch of classes, it can get mightily confused. 

Please try in a new scratch org, or new DE org.
