### ISSUE TITLE
Homepage has an error in retrieving data if there are already apex classes in the org

### ISSUE THREAD

**Issue by patrickXing-au** [trailheadapps/apex-recipes#422]
### Summary

Hi there, 
After I installed the app, the homepage has an error in retrieving data if there are already apex classes in the org. I did some investigation and found that getGroupFromClassBody method uses a regular expression to match the group name. However, the groupName for the existing apex class name was assigned as '            :'. 
I fix the code by adding`  if (groupName.trim()==':') {return 'Local Apex Classes';}` before line 35. But I'm not sure if this is a  good way of fixing this issue. Please let me know your thoughts on this.  The screenshots were attached below.

![image](https://github.com/trailheadapps/apex-recipes/assets/48072759/527ca887-5017-4e13-9e0c-73ef2181d027)
![image](https://github.com/trailheadapps/apex-recipes/assets/48072759/58a7d61a-c317-47cb-ad87-7fcd8e1f8afd)

Regards,
Patrick

### Salesforce Org Type

Trailhead Playground

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msrivastav13** [comment]
@patrickXing-au I have decided to not work on this issue. The reason is this is a very edge case. We cannot anticipate and add logic by number of combinations of group names with special characters one can have in the org. 

You have class with ":", someone will have ',' and some may have '^' and may more. We always recommend apex-recipes to install in a new org.

Reopen the issue if you feel strongly about it and have other ideas.
