### ISSUE TITLE
Data.com fields required in Sandbox.

### ISSUE THREAD

**Issue by aaronmattern** [trailheadapps/apex-recipes#8]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Browsed to link in instructions for Installing with unlocked package:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3g000000kdzQAAQ
2. Changed login.salesforce.com to test.salesforce.com.  
3. Authenticated successfully to my org. 
4. Attempted to install for all users.

### Expected result

Package installed correctly into Sandbox

### Actual result

Install failed when installing package.  Received the errors:
1. (Apex_Recipes) In field: field - no CustomField named Account.DandbCompanyId found
Apex_Recipes: In field: field - no CustomField named Account.DandbCompanyId found

2. (Provides_Read_Only_Access_to_Account_and_All_Fields) In field: field - no CustomField named Account.CleanStatus found
Provides_Read_Only_Access_to_Account_and_All_Fields: In field: field - no CustomField named Account.CleanStatus found

### Additional information

It appears these are fields added by data.com.  We don't use it, and don't have them in our orgs. However, it seems these two field references are only in the permission set.  It's probably not necessary to have them in there.  If you remove the reference, it'd probably install fine.

**Comment by aaronmattern** [comment]
I removed the reference to these fields, as well as.  Not sure why my org doesn't have them.  Finally got the package installed via CLI.

Account.DunsNumber 
Account.NaicsCode 
Account.NaicsDesc
Account.OperatingHoursId
Account.TradeStyle
Account.YearStarted

**Comment by guivlm** [comment]
> I removed the reference to these fields, as well as. Not sure why my org doesn't have them. Finally got the package installed via CLI.
> 
> Account.DunsNumber
> Account.NaicsCode
> Account.NaicsDesc
> Account.OperatingHoursId
> Account.TradeStyle
> Account.YearStarted

How have you removed that @aaronmattern? Having the error message as you faced.

**Comment by aaronmattern** [comment]
@guivlm 

Yes, this allowed me to at least deploy the package into my sandbox.  

However,when I launch the app I'm getting another error:
Regex too complicated

**Comment by guivlm** [comment]
> @guivlm
> 
> Yes, this allowed me to at least deploy the package into my sandbox.
> 
> However, when I launch the app I'm getting another error:
> Regex too complicated

@aaronmattern Thank you for helping me with the deploy. It worked.
Now I'm facing the same issue as you.

![image](https://user-images.githubusercontent.com/20449025/96044812-654dda80-0e47-11eb-9010-cc486d3850cc.png)

**Comment by codefriar** [comment]
@aaronmattern @guivlm, 

Are both of you installing this into an otherwise pre-populated sandbox?

A little bit of background:
Apex Recipes only really ships the actual .cls files. The UI components here interact with those classes generating the Docs, and groupings from the doc blocks in the code itself. 

The RecipeTreeViewController is currently scoped to populate the tree view with *all* the apex classes available in the org that do not match our test class naming convention. If you have a bunch of other classes in the org, or you do not follow our test class naming convention, then this can happen. 

In the near term, I suggest you use Apex Recipes in a net-new Dev org, or Scratch org.
In the longer term, I'm looking at namespacing the Apex Recipes classes so this doesn't happen.

**Comment by aaronmattern** [comment]
Yeah, I was trying to use it in a dev sandbox of my company.  I'll try it in a scratch org, dev org, or playground in the future.

**Comment by codefriar** [comment]
@aaronmattern - I've a PR in to fix this, but I still recommend you using a dedicated scratch org for this.
